name = "tazmany-api-relay"
main = "worker/tazmany-api-relay.js"
compatibility_date = "2026-08-24"

[vars]
APPS_SCRIPT_URL = "REEMPLAZAR_CON_URL_APPS_SCRIPT_TERMINADA_EN_EXEC"
ALLOWED_ORIGINS = "https://jeffersonmgr07.github.io"
