var TAZMANY_CONFIG = Object.freeze({
  APP_NAME: 'Tazmany',
  VERSION: '0.3.11',
  TIME_ZONE: 'America/Lima',
  CURRENCY: 'PEN',
  DEFAULT_CITY_ID: 'city-lima',
  DEFAULT_PUBLIC_LOGO_URL: 'https://tazmany.com/assets/brand/tazmany-logo.png?v=0.3.11',
  CACHE_SECONDS: 300,
  SCRIPT_PROPERTIES: Object.freeze({
    SPREADSHEET_ID: 'TAZMANY_SPREADSHEET_ID',
    DRIVE_FOLDER_ID: 'TAZMANY_DRIVE_FOLDER_ID',
    ENVIRONMENT: 'TAZMANY_ENVIRONMENT',
    LOGO_URL: 'TAZMANY_LOGO_URL',
    AUTH_PEPPER: 'TAZMANY_AUTH_PEPPER',
    GOOGLE_CLIENT_ID: 'TAZMANY_GOOGLE_CLIENT_ID',
    GOOGLE_VERIFY_MODE: 'TAZMANY_GOOGLE_VERIFY_MODE',
    GOOGLE_VERIFY_URL: 'TAZMANY_GOOGLE_VERIFY_URL',
    GOOGLE_VERIFY_RELAY_SECRET: 'TAZMANY_GOOGLE_VERIFY_RELAY_SECRET',
    API_RELAY_SECRET: 'TAZMANY_API_RELAY_SECRET',
    ALLOWED_FRONTEND_ORIGINS: 'TAZMANY_ALLOWED_FRONTEND_ORIGINS',
    SESSION_TTL_HOURS: 'TAZMANY_SESSION_TTL_HOURS',
    OTP_TTL_MINUTES: 'TAZMANY_OTP_TTL_MINUTES',
    OTP_MAX_ATTEMPTS: 'TAZMANY_OTP_MAX_ATTEMPTS',
    TERMS_VERSION: 'TAZMANY_TERMS_VERSION',
    PRIVACY_VERSION: 'TAZMANY_PRIVACY_VERSION'
  }),
  PUBLIC_VIEWS: Object.freeze(['home', 'customer', 'merchant', 'admin']),
  CAMPAIGN_PUBLIC_STATES: Object.freeze(['ACTIVA', 'PROGRAMADA', 'AGOTADA']),
  FEATURES: Object.freeze({
    MERCHANT_ACQUISITION_PUBLIC: false,
    CHECKOUT_ENABLED: false,
    CLUB_BILLING_ENABLED: false,
    INTERNAL_NOTICES_VISIBLE: false
  })
});

function getAppConfig_() {
  var properties = PropertiesService.getScriptProperties();
  return {
    appName: TAZMANY_CONFIG.APP_NAME,
    version: TAZMANY_CONFIG.VERSION,
    environment: properties.getProperty(TAZMANY_CONFIG.SCRIPT_PROPERTIES.ENVIRONMENT) || 'development',
    logoUrl: properties.getProperty(TAZMANY_CONFIG.SCRIPT_PROPERTIES.LOGO_URL) || TAZMANY_CONFIG.DEFAULT_PUBLIC_LOGO_URL,
    currency: TAZMANY_CONFIG.CURRENCY,
    timeZone: TAZMANY_CONFIG.TIME_ZONE,
    features: {
      merchantAcquisitionPublic: TAZMANY_CONFIG.FEATURES.MERCHANT_ACQUISITION_PUBLIC,
      checkoutEnabled: TAZMANY_CONFIG.FEATURES.CHECKOUT_ENABLED,
      clubBillingEnabled: TAZMANY_CONFIG.FEATURES.CLUB_BILLING_ENABLED,
      internalNoticesVisible: TAZMANY_CONFIG.FEATURES.INTERNAL_NOTICES_VISIBLE
    },
    auth: {
      googleClientId: properties.getProperty(TAZMANY_CONFIG.SCRIPT_PROPERTIES.GOOGLE_CLIENT_ID) || '',
      googleEnabled: Boolean(properties.getProperty(TAZMANY_CONFIG.SCRIPT_PROPERTIES.GOOGLE_CLIENT_ID)),
      otpEnabled: true,
      termsVersion: properties.getProperty(TAZMANY_CONFIG.SCRIPT_PROPERTIES.TERMS_VERSION) || '2026-08-27',
      privacyVersion: properties.getProperty(TAZMANY_CONFIG.SCRIPT_PROPERTIES.PRIVACY_VERSION) || '2026-08-27'
    },
    club: { name: 'Club Tazmany', status: 'COMING_SOON' }
  };
}
